package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type LocaleFile struct {
	Trad map[string]interface{} `json:"trad"`
}

func capitalize(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func main() {
	dir := "../../locales/en-US"

	var out bytes.Buffer

	out.WriteString("// Code generated by generator/main.go; DO NOT EDIT.\n")
	out.WriteString("package locales\n\n")
	out.WriteString("import (\n\t\"encoding/json\"\n\t\"github.com/disgoorg/disgo/discord\"\n)\n\n")

	out.WriteString("func unmarshalTrad(command string, raw []byte) (any, error) {\n")
	out.WriteString("\tswitch command {\n")

	var funcs bytes.Buffer

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".json") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return err
		}

		var lf LocaleFile
		if err := json.Unmarshal(content, &lf); err != nil {
			return err
		}

		relPath, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		parts := strings.Split(filepath.ToSlash(relPath), "/")
		if len(parts) == 0 {
			return nil
		}

		baseName := strings.TrimSuffix(info.Name(), ".json")
		
		cmdName := baseName
		if parts[0] == "modules" {
			cmdName = "module_" + baseName
		}

		structPrefix := ""
		if parts[0] == "modules" {
			structPrefix = "Module"
		}
		structName := structPrefix + capitalize(baseName) + "Trad"

		funcs.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		for key := range lf.Trad {
			funcs.WriteString(fmt.Sprintf("\t%s string `json:\"%s\"`\n", capitalize(key), key))
		}
		funcs.WriteString("}\n\n")

		funcs.WriteString(fmt.Sprintf("func Get%s(locale discord.Locale) %s {\n", capitalize(cmdName), structName))
		funcs.WriteString(fmt.Sprintf("\tif l, ok := localizations[locale]; ok {\n"))
		funcs.WriteString(fmt.Sprintf("\t\tif t, ok := l[\"%s\"].(%s); ok { return t }\n", cmdName, structName))
		funcs.WriteString("\t}\n")
		funcs.WriteString(fmt.Sprintf("\tif l, ok := localizations[discord.LocaleEnglishUS]; ok {\n"))
		funcs.WriteString(fmt.Sprintf("\t\tif t, ok := l[\"%s\"].(%s); ok { return t }\n", cmdName, structName))
		funcs.WriteString("\t}\n")
		funcs.WriteString(fmt.Sprintf("\treturn %s{}\n", structName))
		funcs.WriteString("}\n\n")

		out.WriteString(fmt.Sprintf("\tcase \"%s\":\n", cmdName))
		out.WriteString(fmt.Sprintf("\t\tvar t %s\n", structName))
		out.WriteString("\t\terr := json.Unmarshal(raw, &t)\n")
		out.WriteString("\t\treturn t, err\n")

		return nil
	})

	if err != nil {
		panic(err)
	}

	out.WriteString("\tdefault:\n")
	out.WriteString("\t\treturn nil, nil\n")
	out.WriteString("\t}\n}\n\n")

	out.Write(funcs.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Println(out.String())
		panic(err)
	}

	err = ioutil.WriteFile("generated.go", formatted, 0644)
	if err != nil {
		panic(err)
	}
}
