package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"path/filepath"
)

func main() {
	modulesDir := "."
	entries, err := ioutil.ReadDir(modulesDir)
	if err != nil {
		panic(err)
	}

	var imports []string
	for _, entry := range entries {
		if entry.IsDir() && entry.Name() != "generator" {
			imports = append(imports, fmt.Sprintf("\t_ \"onyx/bot/modules/%s\"", entry.Name()))
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by bot/modules/generator/main.go; DO NOT EDIT.\n")
	out.WriteString("package modules\n\n")
	out.WriteString("//go:generate go run generator/main.go\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"onyx/bot/core\"\n\n")
	for _, imp := range imports {
		out.WriteString(imp + "\n")
	}
	out.WriteString(")\n\n")
	out.WriteString("var RegisteredModules = core.RegisteredModules\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Println(out.String())
		panic(err)
	}

	target := filepath.Join(modulesDir, "registry.go")
	if err := os.WriteFile(target, formatted, 0644); err != nil {
		panic(err)
	}
}
