// Code generated by bot/modules/generator/main.go; DO NOT EDIT.
package modules

//go:generate go run generator/main.go

import (
	"onyx/bot/core"

	_ "onyx/bot/modules/channelcounter"
	_ "onyx/bot/modules/freegames"
	_ "onyx/bot/modules/logging"
	_ "onyx/bot/modules/safety"
	_ "onyx/bot/modules/socialnotifs"
	_ "onyx/bot/modules/suggestion"
	_ "onyx/bot/modules/translation"
	_ "onyx/bot/modules/welcome"
	_ "onyx/bot/modules/wizzard"
)

var RegisteredModules = core.RegisteredModules
