// Code generated by generator/main.go; DO NOT EDIT.
package locales

import (
	"encoding/json"
	"github.com/disgoorg/disgo/discord"
)

func unmarshalTrad(command string, raw []byte) (any, error) {
	switch command {
	case "advice":
		var t AdviceTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "agify":
		var t AgifyTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "ascii":
		var t AsciiTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "color":
		var t ColorTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "eightball":
		var t EightballTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "emoji":
		var t EmojiTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "funfact":
		var t FunfactTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "github":
		var t GithubTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "math":
		var t MathTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "meme":
		var t MemeTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "nasa":
		var t NasaTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "npm":
		var t NpmTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "quote":
		var t QuoteTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "upsidedown":
		var t UpsidedownTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "urban":
		var t UrbanTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "bot":
		var t BotTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "ping":
		var t PingTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "translate":
		var t TranslateTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "interaction":
		var t InteractionTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_ChannelCounter":
		var t ModuleChannelCounterTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_LoggingModule":
		var t ModuleLoggingModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_SafetyModule":
		var t ModuleSafetyModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_TranslationModule":
		var t ModuleTranslationModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_WelcomeModule":
		var t ModuleWelcomeModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_WizzardModule":
		var t ModuleWizzardModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	default:
		return nil, nil
	}
}

type AdviceTrad struct {
	Advice string `json:"advice"`
	Title  string `json:"title"`
}

func GetAdvice(locale discord.Locale) AdviceTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["advice"].(AdviceTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["advice"].(AdviceTrad); ok {
			return t
		}
	}
	return AdviceTrad{}
}

type AgifyTrad struct {
	Title string `json:"title"`
	Age   string `json:"age"`
}

func GetAgify(locale discord.Locale) AgifyTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["agify"].(AgifyTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["agify"].(AgifyTrad); ok {
			return t
		}
	}
	return AgifyTrad{}
}

type AsciiTrad struct {
	Title string `json:"title"`
	Error string `json:"error"`
}

func GetAscii(locale discord.Locale) AsciiTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["ascii"].(AsciiTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["ascii"].(AsciiTrad); ok {
			return t
		}
	}
	return AsciiTrad{}
}

type ColorTrad struct {
	Hsv     string `json:"hsv"`
	Cmyk    string `json:"cmyk"`
	Decimal string `json:"decimal"`
	Hex     string `json:"hex"`
	Rgb     string `json:"rgb"`
	Hsl     string `json:"hsl"`
}

func GetColor(locale discord.Locale) ColorTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["color"].(ColorTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["color"].(ColorTrad); ok {
			return t
		}
	}
	return ColorTrad{}
}

type EightballTrad struct {
	Title    string `json:"title"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

func GetEightball(locale discord.Locale) EightballTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["eightball"].(EightballTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["eightball"].(EightballTrad); ok {
			return t
		}
	}
	return EightballTrad{}
}

type EmojiTrad struct {
	Emojify_error string `json:"emojify_error"`
	Emojify_title string `json:"emojify_title"`
	Mix_error     string `json:"mix_error"`
	Mix_title     string `json:"mix_title"`
	Random_error  string `json:"random_error"`
	Random_title  string `json:"random_title"`
}

func GetEmoji(locale discord.Locale) EmojiTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["emoji"].(EmojiTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["emoji"].(EmojiTrad); ok {
			return t
		}
	}
	return EmojiTrad{}
}

type FunfactTrad struct {
	Title  string `json:"title"`
	Text   string `json:"text"`
	Source string `json:"source"`
}

func GetFunfact(locale discord.Locale) FunfactTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["funfact"].(FunfactTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["funfact"].(FunfactTrad); ok {
			return t
		}
	}
	return FunfactTrad{}
}

type GithubTrad struct {
	None         string `json:"none"`
	User_page    string `json:"user_page"`
	Repo_title   string `json:"repo_title"`
	Repo_desc    string `json:"repo_desc"`
	Repo_license string `json:"repo_license"`
	User_title   string `json:"user_title"`
	Repo_button  string `json:"repo_button"`
	No_desc      string `json:"no_desc"`
	Unknown      string `json:"unknown"`
}

func GetGithub(locale discord.Locale) GithubTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["github"].(GithubTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["github"].(GithubTrad); ok {
			return t
		}
	}
	return GithubTrad{}
}

type MathTrad struct {
	Title      string `json:"title"`
	Expression string `json:"expression"`
	Result     string `json:"result"`
}

func GetMath(locale discord.Locale) MathTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["math"].(MathTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["math"].(MathTrad); ok {
			return t
		}
	}
	return MathTrad{}
}

type MemeTrad struct {
	Title      string `json:"title"`
	Meme_title string `json:"meme_title"`
	Author     string `json:"author"`
}

func GetMeme(locale discord.Locale) MemeTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["meme"].(MemeTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["meme"].(MemeTrad); ok {
			return t
		}
	}
	return MemeTrad{}
}

type NasaTrad struct {
	Iss_title    string `json:"iss_title"`
	Iss_position string `json:"iss_position"`
	Iss_altitude string `json:"iss_altitude"`
	Iss_updated  string `json:"iss_updated"`
	Apod_title   string `json:"apod_title"`
	Source       string `json:"source"`
}

func GetNasa(locale discord.Locale) NasaTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["nasa"].(NasaTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["nasa"].(NasaTrad); ok {
			return t
		}
	}
	return NasaTrad{}
}

type NpmTrad struct {
	Not_found      string `json:"not_found"`
	None           string `json:"none"`
	Npm_page       string `json:"npm_page"`
	Na             string `json:"na"`
	Title          string `json:"title"`
	Downloads      string `json:"downloads"`
	Unknown        string `json:"unknown"`
	Repository     string `json:"repository"`
	Desc           string `json:"desc"`
	Last_published string `json:"last_published"`
}

func GetNpm(locale discord.Locale) NpmTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["npm"].(NpmTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["npm"].(NpmTrad); ok {
			return t
		}
	}
	return NpmTrad{}
}

type QuoteTrad struct {
	Quote  string `json:"quote"`
	Author string `json:"author"`
	Title  string `json:"title"`
}

func GetQuote(locale discord.Locale) QuoteTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["quote"].(QuoteTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["quote"].(QuoteTrad); ok {
			return t
		}
	}
	return QuoteTrad{}
}

type UpsidedownTrad struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

func GetUpsidedown(locale discord.Locale) UpsidedownTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["upsidedown"].(UpsidedownTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["upsidedown"].(UpsidedownTrad); ok {
			return t
		}
	}
	return UpsidedownTrad{}
}

type UrbanTrad struct {
	Author     string `json:"author"`
	Source     string `json:"source"`
	Title      string `json:"title"`
	Definition string `json:"definition"`
	Example    string `json:"example"`
}

func GetUrban(locale discord.Locale) UrbanTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["urban"].(UrbanTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["urban"].(UrbanTrad); ok {
			return t
		}
	}
	return UrbanTrad{}
}

type BotTrad struct {
	Db_size           string `json:"db_size"`
	Stats             string `json:"stats"`
	Title             string `json:"title"`
	Description       string `json:"description"`
	Version_onyx      string `json:"version_onyx"`
	Programming_title string `json:"programming_title"`
	Website           string `json:"website"`
	Invite_me         string `json:"invite_me"`
	Error_self_user   string `json:"error_self_user"`
	Stats_title       string `json:"stats_title"`
	Details_title     string `json:"details_title"`
	Last_boot         string `json:"last_boot"`
	Versions          string `json:"versions"`
}

func GetBot(locale discord.Locale) BotTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["bot"].(BotTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["bot"].(BotTrad); ok {
			return t
		}
	}
	return BotTrad{}
}

type PingTrad struct {
	Db_latency      string `json:"db_latency"`
	Title           string `json:"title"`
	Gateway_latency string `json:"gateway_latency"`
	Rest_latency    string `json:"rest_latency"`
}

func GetPing(locale discord.Locale) PingTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["ping"].(PingTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["ping"].(PingTrad); ok {
			return t
		}
	}
	return PingTrad{}
}

type TranslateTrad struct {
	Footer string `json:"footer"`
}

func GetTranslate(locale discord.Locale) TranslateTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["translate"].(TranslateTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["translate"].(TranslateTrad); ok {
			return t
		}
	}
	return TranslateTrad{}
}

type InteractionTrad struct {
	Not_allowed_modal     string `json:"not_allowed_modal"`
	Not_allowed_component string `json:"not_allowed_component"`
}

func GetInteraction(locale discord.Locale) InteractionTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["interaction"].(InteractionTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["interaction"].(InteractionTrad); ok {
			return t
		}
	}
	return InteractionTrad{}
}

type ModuleChannelCounterTrad struct {
}

func GetModule_ChannelCounter(locale discord.Locale) ModuleChannelCounterTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_ChannelCounter"].(ModuleChannelCounterTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_ChannelCounter"].(ModuleChannelCounterTrad); ok {
			return t
		}
	}
	return ModuleChannelCounterTrad{}
}

type ModuleLoggingModuleTrad struct {
	InviteCreate  ModuleLoggingModuleTrad_InviteCreate  `json:"inviteCreate"`
	MessageUpdate ModuleLoggingModuleTrad_MessageUpdate `json:"messageUpdate"`
	EmojiUpdate   ModuleLoggingModuleTrad_EmojiUpdate   `json:"emojiUpdate"`
	GuildUpdate   ModuleLoggingModuleTrad_GuildUpdate   `json:"guildUpdate"`
	ChannelCreate ModuleLoggingModuleTrad_ChannelCreate `json:"channelCreate"`
	ChannelDelete ModuleLoggingModuleTrad_ChannelDelete `json:"channelDelete"`
	RoleUpdate    ModuleLoggingModuleTrad_RoleUpdate    `json:"roleUpdate"`
	EmojiCreate   ModuleLoggingModuleTrad_EmojiCreate   `json:"emojiCreate"`
	MessageDelete ModuleLoggingModuleTrad_MessageDelete `json:"messageDelete"`
	ThreadUpdate  ModuleLoggingModuleTrad_ThreadUpdate  `json:"threadUpdate"`
	ChannelUpdate ModuleLoggingModuleTrad_ChannelUpdate `json:"channelUpdate"`
	RoleCreate    ModuleLoggingModuleTrad_RoleCreate    `json:"roleCreate"`
	RoleDelete    ModuleLoggingModuleTrad_RoleDelete    `json:"roleDelete"`
	MemberJoin    ModuleLoggingModuleTrad_MemberJoin    `json:"memberJoin"`
	MemberUpdate  ModuleLoggingModuleTrad_MemberUpdate  `json:"memberUpdate"`
	StickerDelete ModuleLoggingModuleTrad_StickerDelete `json:"stickerDelete"`
	MemberLeave   ModuleLoggingModuleTrad_MemberLeave   `json:"memberLeave"`
	BanAdd        ModuleLoggingModuleTrad_BanAdd        `json:"banAdd"`
	BanRemove     ModuleLoggingModuleTrad_BanRemove     `json:"banRemove"`
	EmojiDelete   ModuleLoggingModuleTrad_EmojiDelete   `json:"emojiDelete"`
	StickerCreate ModuleLoggingModuleTrad_StickerCreate `json:"stickerCreate"`
	InviteDelete  ModuleLoggingModuleTrad_InviteDelete  `json:"inviteDelete"`
	ThreadCreate  ModuleLoggingModuleTrad_ThreadCreate  `json:"threadCreate"`
	ThreadDelete  ModuleLoggingModuleTrad_ThreadDelete  `json:"threadDelete"`
	StickerUpdate ModuleLoggingModuleTrad_StickerUpdate `json:"stickerUpdate"`
}

type ModuleLoggingModuleTrad_ChannelUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_ChannelUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ChannelUpdate_States struct {
	Name             string `json:"name"`
	Topic            string `json:"topic"`
	Nsfw             string `json:"nsfw"`
	RateLimitPerUser string `json:"rateLimitPerUser"`
}

type ModuleLoggingModuleTrad_RoleCreate struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleCreate_States struct {
	Color string `json:"color"`
	Name  string `json:"name"`
}

type ModuleLoggingModuleTrad_RoleDelete struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_MemberJoin struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_MemberJoin_States `json:"states"`
}

type ModuleLoggingModuleTrad_MemberJoin_States struct {
	User           string `json:"user"`
	AccountCreated string `json:"accountCreated"`
}

type ModuleLoggingModuleTrad_MemberUpdate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_MemberUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_MemberUpdate_States struct {
	User     string `json:"user"`
	Nickname string `json:"nickname"`
	Roles    string `json:"roles"`
	Avatar   string `json:"avatar"`
}

type ModuleLoggingModuleTrad_StickerDelete struct {
	States ModuleLoggingModuleTrad_StickerDelete_States `json:"states"`
	Title  string                                       `json:"title"`
}

type ModuleLoggingModuleTrad_StickerDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_MemberLeave struct {
	States ModuleLoggingModuleTrad_MemberLeave_States `json:"states"`
	Title  string                                     `json:"title"`
}

type ModuleLoggingModuleTrad_MemberLeave_States struct {
	User string `json:"user"`
}

type ModuleLoggingModuleTrad_BanAdd struct {
	Title  string                                `json:"title"`
	States ModuleLoggingModuleTrad_BanAdd_States `json:"states"`
}

type ModuleLoggingModuleTrad_BanAdd_States struct {
	User   string `json:"user"`
	Reason string `json:"reason"`
}

type ModuleLoggingModuleTrad_BanRemove struct {
	Title  string                                   `json:"title"`
	States ModuleLoggingModuleTrad_BanRemove_States `json:"states"`
}

type ModuleLoggingModuleTrad_BanRemove_States struct {
	User string `json:"user"`
}

type ModuleLoggingModuleTrad_EmojiDelete struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_StickerCreate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_StickerCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_StickerCreate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_InviteDelete struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_InviteDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_InviteDelete_States struct {
	Code string `json:"code"`
}

type ModuleLoggingModuleTrad_ThreadCreate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_ThreadCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ThreadCreate_States struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Parent string `json:"parent"`
}

type ModuleLoggingModuleTrad_ThreadDelete struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_ThreadDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_ThreadDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_StickerUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_StickerUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_StickerUpdate_States struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleLoggingModuleTrad_InviteCreate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_InviteCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_InviteCreate_States struct {
	MaxAge  string `json:"maxAge"`
	Code    string `json:"code"`
	Channel string `json:"channel"`
	Inviter string `json:"inviter"`
	MaxUses string `json:"maxUses"`
}

type ModuleLoggingModuleTrad_MessageUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_MessageUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_MessageUpdate_States struct {
	OldContent string `json:"oldContent"`
	NewContent string `json:"newContent"`
	Author     string `json:"author"`
	Channel    string `json:"channel"`
}

type ModuleLoggingModuleTrad_EmojiUpdate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiUpdate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_GuildUpdate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_GuildUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_GuildUpdate_States struct {
	Description       string `json:"description"`
	VerificationLevel string `json:"verificationLevel"`
	Icon              string `json:"icon"`
	Banner            string `json:"banner"`
	Name              string `json:"name"`
}

type ModuleLoggingModuleTrad_ChannelCreate struct {
	States ModuleLoggingModuleTrad_ChannelCreate_States `json:"states"`
	Title  string                                       `json:"title"`
}

type ModuleLoggingModuleTrad_ChannelCreate_States struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type ModuleLoggingModuleTrad_ChannelDelete struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_ChannelDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_ChannelDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_RoleUpdate struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleUpdate_States struct {
	Permissions string `json:"permissions"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Hoist       string `json:"hoist"`
	Mentionable string `json:"mentionable"`
}

type ModuleLoggingModuleTrad_EmojiCreate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiCreate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_MessageDelete struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_MessageDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_MessageDelete_States struct {
	Author  string `json:"author"`
	Channel string `json:"channel"`
	Content string `json:"content"`
}

type ModuleLoggingModuleTrad_ThreadUpdate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_ThreadUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ThreadUpdate_States struct {
	Name                string `json:"name"`
	Archived            string `json:"archived"`
	Locked              string `json:"locked"`
	AutoArchiveDuration string `json:"autoArchiveDuration"`
}

func GetModule_LoggingModule(locale discord.Locale) ModuleLoggingModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_LoggingModule"].(ModuleLoggingModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_LoggingModule"].(ModuleLoggingModuleTrad); ok {
			return t
		}
	}
	return ModuleLoggingModuleTrad{}
}

type ModuleSafetyModuleTrad struct {
	Phishing_censored_title       string `json:"phishing_censored_title"`
	Phishing_censored_description string `json:"phishing_censored_description"`
}

func GetModule_SafetyModule(locale discord.Locale) ModuleSafetyModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_SafetyModule"].(ModuleSafetyModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_SafetyModule"].(ModuleSafetyModuleTrad); ok {
			return t
		}
	}
	return ModuleSafetyModuleTrad{}
}

type ModuleTranslationModuleTrad struct {
}

func GetModule_TranslationModule(locale discord.Locale) ModuleTranslationModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_TranslationModule"].(ModuleTranslationModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_TranslationModule"].(ModuleTranslationModuleTrad); ok {
			return t
		}
	}
	return ModuleTranslationModuleTrad{}
}

type ModuleWelcomeModuleTrad struct {
	Card_t2            string `json:"card_t2"`
	Embed_title        string `json:"embed_title"`
	Embed_footer       string `json:"embed_footer"`
	Leave_card_t1      string `json:"leave_card_t1"`
	Leave_card_t2      string `json:"leave_card_t2"`
	Leave_embed_title  string `json:"leave_embed_title"`
	Leave_embed_footer string `json:"leave_embed_footer"`
	Card_t1            string `json:"card_t1"`
}

func GetModule_WelcomeModule(locale discord.Locale) ModuleWelcomeModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_WelcomeModule"].(ModuleWelcomeModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_WelcomeModule"].(ModuleWelcomeModuleTrad); ok {
			return t
		}
	}
	return ModuleWelcomeModuleTrad{}
}

type ModuleWizzardModuleTrad struct {
	Spells ModuleWizzardModuleTrad_Spells `json:"spells"`
}

type ModuleWizzardModuleTrad_Spells struct {
	Finiteincantatem      ModuleWizzardModuleTrad_Spells_Finiteincantatem      `json:"finiteincantatem"`
	Cistemaperio          ModuleWizzardModuleTrad_Spells_Cistemaperio          `json:"cistemaperio"`
	Fenestra              ModuleWizzardModuleTrad_Spells_Fenestra              `json:"fenestra"`
	Molliare              ModuleWizzardModuleTrad_Spells_Molliare              `json:"molliare"`
	Serpensortia          ModuleWizzardModuleTrad_Spells_Serpensortia          `json:"serpensortia"`
	Volateascendere       ModuleWizzardModuleTrad_Spells_Volateascendere       `json:"volateascendere"`
	Brachiumemendo        ModuleWizzardModuleTrad_Spells_Brachiumemendo        `json:"brachiumemendo"`
	Incarcerem            ModuleWizzardModuleTrad_Spells_Incarcerem            `json:"incarcerem"`
	Lacarnuminflammari    ModuleWizzardModuleTrad_Spells_Lacarnuminflammari    `json:"lacarnuminflammari"`
	Meteorribilisrecanto  ModuleWizzardModuleTrad_Spells_Meteorribilisrecanto  `json:"meteorribilisrecanto"`
	Mobilicorpus          ModuleWizzardModuleTrad_Spells_Mobilicorpus          `json:"mobilicorpus"`
	Protegomaxima         ModuleWizzardModuleTrad_Spells_Protegomaxima         `json:"protegomaxima"`
	Specialisrevelio      ModuleWizzardModuleTrad_Spells_Specialisrevelio      `json:"specialisrevelio"`
	Assurdiato            ModuleWizzardModuleTrad_Spells_Assurdiato            `json:"assurdiato"`
	Surgito               ModuleWizzardModuleTrad_Spells_Surgito               `json:"surgito"`
	Anapneo               ModuleWizzardModuleTrad_Spells_Anapneo               `json:"anapneo"`
	Avadakedavra          ModuleWizzardModuleTrad_Spells_Avadakedavra          `json:"avadakedavra"`
	Endoloris             ModuleWizzardModuleTrad_Spells_Endoloris             `json:"endoloris"`
	Fiantoduri            ModuleWizzardModuleTrad_Spells_Fiantoduri            `json:"fiantoduri"`
	Gemino                ModuleWizzardModuleTrad_Spells_Gemino                `json:"gemino"`
	Impervius             ModuleWizzardModuleTrad_Spells_Impervius             `json:"impervius"`
	Levicorpus            ModuleWizzardModuleTrad_Spells_Levicorpus            `json:"levicorpus"`
	Mobiliarbus           ModuleWizzardModuleTrad_Spells_Mobiliarbus           `json:"mobiliarbus"`
	Enervatum             ModuleWizzardModuleTrad_Spells_Enervatum             `json:"enervatum"`
	Impero                ModuleWizzardModuleTrad_Spells_Impero                `json:"impero"`
	Incendio              ModuleWizzardModuleTrad_Spells_Incendio              `json:"incendio"`
	Piertotumlocomotor    ModuleWizzardModuleTrad_Spells_Piertotumlocomotor    `json:"piertotumlocomotor"`
	Revelio               ModuleWizzardModuleTrad_Spells_Revelio               `json:"revelio"`
	Avensegium            ModuleWizzardModuleTrad_Spells_Avensegium            `json:"avensegium"`
	Bloclang              ModuleWizzardModuleTrad_Spells_Bloclang              `json:"bloclang"`
	Rictusempra           ModuleWizzardModuleTrad_Spells_Rictusempra           `json:"rictusempra"`
	Veraverto             ModuleWizzardModuleTrad_Spells_Veraverto             `json:"veraverto"`
	Slugvomitingcharm     ModuleWizzardModuleTrad_Spells_Slugvomitingcharm     `json:"slugvomitingcharm"`
	Oscausi               ModuleWizzardModuleTrad_Spells_Oscausi               `json:"oscausi"`
	Waddiwasi             ModuleWizzardModuleTrad_Spells_Waddiwasi             `json:"waddiwasi"`
	Avis                  ModuleWizzardModuleTrad_Spells_Avis                  `json:"avis"`
	Fidelitas             ModuleWizzardModuleTrad_Spells_Fidelitas             `json:"fidelitas"`
	Prioriincantatum      ModuleWizzardModuleTrad_Spells_Prioriincantatum      `json:"prioriincantatum"`
	Dentesaugmento        ModuleWizzardModuleTrad_Spells_Dentesaugmento        `json:"dentesaugmento"`
	Nox                   ModuleWizzardModuleTrad_Spells_Nox                   `json:"nox"`
	Recurvite             ModuleWizzardModuleTrad_Spells_Recurvite             `json:"recurvite"`
	Reparo                ModuleWizzardModuleTrad_Spells_Reparo                `json:"reparo"`
	Accio                 ModuleWizzardModuleTrad_Spells_Accio                 `json:"accio"`
	Apparevestigium       ModuleWizzardModuleTrad_Spells_Apparevestigium       `json:"apparevestigium"`
	Episkey               ModuleWizzardModuleTrad_Spells_Episkey               `json:"episkey"`
	Priorincanto          ModuleWizzardModuleTrad_Spells_Priorincanto          `json:"priorincanto"`
	Protegototalum        ModuleWizzardModuleTrad_Spells_Protegototalum        `json:"protegototalum"`
	Repelloinimicium      ModuleWizzardModuleTrad_Spells_Repelloinimicium      `json:"repelloinimicium"`
	Sonorus               ModuleWizzardModuleTrad_Spells_Sonorus               `json:"sonorus"`
	Confundo              ModuleWizzardModuleTrad_Spells_Confundo              `json:"confundo"`
	Dissendium            ModuleWizzardModuleTrad_Spells_Dissendium            `json:"dissendium"`
	Evertestatum          ModuleWizzardModuleTrad_Spells_Evertestatum          `json:"evertestatum"`
	Tarentallegra         ModuleWizzardModuleTrad_Spells_Tarentallegra         `json:"tarentallegra"`
	Deprimo               ModuleWizzardModuleTrad_Spells_Deprimo               `json:"deprimo"`
	Duro                  ModuleWizzardModuleTrad_Spells_Duro                  `json:"duro"`
	Failamalle            ModuleWizzardModuleTrad_Spells_Failamalle            `json:"failamalle"`
	Partistemporus        ModuleWizzardModuleTrad_Spells_Partistemporus        `json:"partistemporus"`
	Ascendio              ModuleWizzardModuleTrad_Spells_Ascendio              `json:"ascendio"`
	Repellomoldum         ModuleWizzardModuleTrad_Spells_Repellomoldum         `json:"repellomoldum"`
	Ventus                ModuleWizzardModuleTrad_Spells_Ventus                `json:"ventus"`
	Araniaexumai          ModuleWizzardModuleTrad_Spells_Araniaexumai          `json:"araniaexumai"`
	Impedimenta           ModuleWizzardModuleTrad_Spells_Impedimenta           `json:"impedimenta"`
	Oppugno               ModuleWizzardModuleTrad_Spells_Oppugno               `json:"oppugno"`
	Alohomora             ModuleWizzardModuleTrad_Spells_Alohomora             `json:"alohomora"`
	Arrestomomentum       ModuleWizzardModuleTrad_Spells_Arrestomomentum       `json:"arrestomomentum"`
	Fulgari               ModuleWizzardModuleTrad_Spells_Fulgari               `json:"fulgari"`
	Hominumrevelio        ModuleWizzardModuleTrad_Spells_Hominumrevelio        `json:"hominumrevelio"`
	Legilimens            ModuleWizzardModuleTrad_Spells_Legilimens            `json:"legilimens"`
	Mutinlutinmalinpesti  ModuleWizzardModuleTrad_Spells_Mutinlutinmalinpesti  `json:"mutinlutinmalinpesti"`
	Surdinam              ModuleWizzardModuleTrad_Spells_Surdinam              `json:"surdinam"`
	Tergeo                ModuleWizzardModuleTrad_Spells_Tergeo                `json:"tergeo"`
	Erigo                 ModuleWizzardModuleTrad_Spells_Erigo                 `json:"erigo"`
	Locomotorbarda        ModuleWizzardModuleTrad_Spells_Locomotorbarda        `json:"locomotorbarda"`
	Protegohorribilis     ModuleWizzardModuleTrad_Spells_Protegohorribilis     `json:"protegohorribilis"`
	Speropatronum         ModuleWizzardModuleTrad_Spells_Speropatronum         `json:"speropatronum"`
	Aguamenti             ModuleWizzardModuleTrad_Spells_Aguamenti             `json:"aguamenti"`
	Reducto               ModuleWizzardModuleTrad_Spells_Reducto               `json:"reducto"`
	Amplificatum          ModuleWizzardModuleTrad_Spells_Amplificatum          `json:"amplificatum"`
	Brachialigo           ModuleWizzardModuleTrad_Spells_Brachialigo           `json:"brachialigo"`
	Caveinimicum          ModuleWizzardModuleTrad_Spells_Caveinimicum          `json:"caveinimicum"`
	Diffindo              ModuleWizzardModuleTrad_Spells_Diffindo              `json:"diffindo"`
	Flambios              ModuleWizzardModuleTrad_Spells_Flambios              `json:"flambios"`
	Revigor               ModuleWizzardModuleTrad_Spells_Revigor               `json:"revigor"`
	Aparecium             ModuleWizzardModuleTrad_Spells_Aparecium             `json:"aparecium"`
	Obscuro               ModuleWizzardModuleTrad_Spells_Obscuro               `json:"obscuro"`
	Orchideus             ModuleWizzardModuleTrad_Spells_Orchideus             `json:"orchideus"`
	Petrificustotalus     ModuleWizzardModuleTrad_Spells_Petrificustotalus     `json:"petrificustotalus"`
	Glisseo               ModuleWizzardModuleTrad_Spells_Glisseo               `json:"glisseo"`
	Harmonianecterepassus ModuleWizzardModuleTrad_Spells_Harmonianecterepassus `json:"harmonianecterepassus"`
	Nebulus               ModuleWizzardModuleTrad_Spells_Nebulus               `json:"nebulus"`
	Riddikulus            ModuleWizzardModuleTrad_Spells_Riddikulus            `json:"riddikulus"`
	Circumrota            ModuleWizzardModuleTrad_Spells_Circumrota            `json:"circumrota"`
	Emancipare            ModuleWizzardModuleTrad_Spells_Emancipare            `json:"emancipare"`
	Expelliarmus          ModuleWizzardModuleTrad_Spells_Expelliarmus          `json:"expelliarmus"`
	Silencio              ModuleWizzardModuleTrad_Spells_Silencio              `json:"silencio"`
	Viperaevanesca        ModuleWizzardModuleTrad_Spells_Viperaevanesca        `json:"viperaevanesca"`
	Expectopatronum       ModuleWizzardModuleTrad_Spells_Expectopatronum       `json:"expectopatronum"`
	Ferula                ModuleWizzardModuleTrad_Spells_Ferula                `json:"ferula"`
	Oubliettes            ModuleWizzardModuleTrad_Spells_Oubliettes            `json:"oubliettes"`
	Periculum             ModuleWizzardModuleTrad_Spells_Periculum             `json:"periculum"`
	Protego               ModuleWizzardModuleTrad_Spells_Protego               `json:"protego"`
	Collaporta            ModuleWizzardModuleTrad_Spells_Collaporta            `json:"collaporta"`
	Confringo             ModuleWizzardModuleTrad_Spells_Confringo             `json:"confringo"`
	Defodio               ModuleWizzardModuleTrad_Spells_Defodio               `json:"defodio"`
	Evanesco              ModuleWizzardModuleTrad_Spells_Evanesco              `json:"evanesco"`
	Locomotormortis       ModuleWizzardModuleTrad_Spells_Locomotormortis       `json:"locomotormortis"`
	Locomotorwibbly       ModuleWizzardModuleTrad_Spells_Locomotorwibbly       `json:"locomotorwibbly"`
	Morsmordre            ModuleWizzardModuleTrad_Spells_Morsmordre            `json:"morsmordre"`
	Stupefix              ModuleWizzardModuleTrad_Spells_Stupefix              `json:"stupefix"`
	Bombardamaxima        ModuleWizzardModuleTrad_Spells_Bombardamaxima        `json:"bombardamaxima"`
	Vulnerasanentur       ModuleWizzardModuleTrad_Spells_Vulnerasanentur       `json:"vulnerasanentur"`
	Wingardiumleviosa     ModuleWizzardModuleTrad_Spells_Wingardiumleviosa     `json:"wingardiumleviosa"`
	Destructum            ModuleWizzardModuleTrad_Spells_Destructum            `json:"destructum"`
	Immobulus             ModuleWizzardModuleTrad_Spells_Immobulus             `json:"immobulus"`
	Protegodiabolica      ModuleWizzardModuleTrad_Spells_Protegodiabolica      `json:"protegodiabolica"`
	Furunculus            ModuleWizzardModuleTrad_Spells_Furunculus            `json:"furunculus"`
	Portus                ModuleWizzardModuleTrad_Spells_Portus                `json:"portus"`
	Reverte               ModuleWizzardModuleTrad_Spells_Reverte               `json:"reverte"`
	Capaciousextremis     ModuleWizzardModuleTrad_Spells_Capaciousextremis     `json:"capaciousextremis"`
	Expulso               ModuleWizzardModuleTrad_Spells_Expulso               `json:"expulso"`
	Aberto                ModuleWizzardModuleTrad_Spells_Aberto                `json:"aberto"`
	Homomorphus           ModuleWizzardModuleTrad_Spells_Homomorphus           `json:"homomorphus"`
	Liberacorpus          ModuleWizzardModuleTrad_Spells_Liberacorpus          `json:"liberacorpus"`
	Salveomaleficia       ModuleWizzardModuleTrad_Spells_Salveomaleficia       `json:"salveomaleficia"`
	Sectumsempra          ModuleWizzardModuleTrad_Spells_Sectumsempra          `json:"sectumsempra"`
}

type ModuleWizzardModuleTrad_Spells_Amplificatum struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Brachialigo struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Caveinimicum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Diffindo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Flambios struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Revigor struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Aparecium struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Obscuro struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Orchideus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Petrificustotalus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Glisseo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Harmonianecterepassus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Nebulus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Riddikulus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Circumrota struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Emancipare struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Expelliarmus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Silencio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Viperaevanesca struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Expectopatronum struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Ferula struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Oubliettes struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Periculum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protego struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Collaporta struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Confringo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Defodio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Evanesco struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Locomotormortis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Locomotorwibbly struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Morsmordre struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Stupefix struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Bombardamaxima struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Vulnerasanentur struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Wingardiumleviosa struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Destructum struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Immobulus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Protegodiabolica struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Furunculus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Portus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Reverte struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Capaciousextremis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Expulso struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Aberto struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Homomorphus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Liberacorpus struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Salveomaleficia struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Sectumsempra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Finiteincantatem struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Cistemaperio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fenestra struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Molliare struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Serpensortia struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Volateascendere struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Brachiumemendo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Incarcerem struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Lacarnuminflammari struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Meteorribilisrecanto struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Mobilicorpus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protegomaxima struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Specialisrevelio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Assurdiato struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Surgito struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Anapneo struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Avadakedavra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Endoloris struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fiantoduri struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Gemino struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Impervius struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Levicorpus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Mobiliarbus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Enervatum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Impero struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Incendio struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Piertotumlocomotor struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Revelio struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Avensegium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Bloclang struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Rictusempra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Veraverto struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Slugvomitingcharm struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Oscausi struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Waddiwasi struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Avis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fidelitas struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Prioriincantatum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Dentesaugmento struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Nox struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Recurvite struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Reparo struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Accio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Apparevestigium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Episkey struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Priorincanto struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Protegototalum struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Repelloinimicium struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Sonorus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Confundo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Dissendium struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Evertestatum struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Tarentallegra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Deprimo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Duro struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Failamalle struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Partistemporus struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Ascendio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Repellomoldum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Ventus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Araniaexumai struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Impedimenta struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Oppugno struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Alohomora struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Arrestomomentum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fulgari struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Hominumrevelio struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Legilimens struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Mutinlutinmalinpesti struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Surdinam struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Tergeo struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Erigo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Locomotorbarda struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protegohorribilis struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Speropatronum struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Aguamenti struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Reducto struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

func GetModule_WizzardModule(locale discord.Locale) ModuleWizzardModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_WizzardModule"].(ModuleWizzardModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_WizzardModule"].(ModuleWizzardModuleTrad); ok {
			return t
		}
	}
	return ModuleWizzardModuleTrad{}
}
