// Code generated by generator/main.go; DO NOT EDIT.
package locales

import (
	"encoding/json"
	"github.com/disgoorg/disgo/discord"
)

func unmarshalTrad(command string, raw []byte) (any, error) {
	switch command {
	case "advice":
		var t AdviceTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "agify":
		var t AgifyTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "ascii":
		var t AsciiTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "color":
		var t ColorTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "eightball":
		var t EightballTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "emoji":
		var t EmojiTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "funfact":
		var t FunfactTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "github":
		var t GithubTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "math":
		var t MathTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "meme":
		var t MemeTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "nasa":
		var t NasaTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "npm":
		var t NpmTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "quote":
		var t QuoteTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "upsidedown":
		var t UpsidedownTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "urban":
		var t UrbanTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "bot":
		var t BotTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "suggestion":
		var t SuggestionTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "reminder":
		var t ReminderTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "ping":
		var t PingTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "translate":
		var t TranslateTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "interaction":
		var t InteractionTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_ChannelCounter":
		var t ModuleChannelCounterTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_FreeGamesModule":
		var t ModuleFreeGamesModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_LoggingModule":
		var t ModuleLoggingModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_SafetyModule":
		var t ModuleSafetyModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_SocialNotifsModule":
		var t ModuleSocialNotifsModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_SuggestionModule":
		var t ModuleSuggestionModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_TranslationModule":
		var t ModuleTranslationModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_WelcomeModule":
		var t ModuleWelcomeModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	case "module_WizzardModule":
		var t ModuleWizzardModuleTrad
		err := json.Unmarshal(raw, &t)
		return t, err
	default:
		return nil, nil
	}
}

type AdviceTrad struct {
	Title  string `json:"title"`
	Advice string `json:"advice"`
}

func GetAdvice(locale discord.Locale) AdviceTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["advice"].(AdviceTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["advice"].(AdviceTrad); ok {
			return t
		}
	}
	return AdviceTrad{}
}

type AgifyTrad struct {
	Title string `json:"title"`
	Age   string `json:"age"`
}

func GetAgify(locale discord.Locale) AgifyTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["agify"].(AgifyTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["agify"].(AgifyTrad); ok {
			return t
		}
	}
	return AgifyTrad{}
}

type AsciiTrad struct {
	Title string `json:"title"`
	Error string `json:"error"`
}

func GetAscii(locale discord.Locale) AsciiTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["ascii"].(AsciiTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["ascii"].(AsciiTrad); ok {
			return t
		}
	}
	return AsciiTrad{}
}

type ColorTrad struct {
	Hsv     string `json:"hsv"`
	Cmyk    string `json:"cmyk"`
	Decimal string `json:"decimal"`
	Hex     string `json:"hex"`
	Rgb     string `json:"rgb"`
	Hsl     string `json:"hsl"`
}

func GetColor(locale discord.Locale) ColorTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["color"].(ColorTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["color"].(ColorTrad); ok {
			return t
		}
	}
	return ColorTrad{}
}

type EightballTrad struct {
	Answer   string `json:"answer"`
	Title    string `json:"title"`
	Question string `json:"question"`
}

func GetEightball(locale discord.Locale) EightballTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["eightball"].(EightballTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["eightball"].(EightballTrad); ok {
			return t
		}
	}
	return EightballTrad{}
}

type EmojiTrad struct {
	Emojify_error string `json:"emojify_error"`
	Emojify_title string `json:"emojify_title"`
	Mix_error     string `json:"mix_error"`
	Mix_title     string `json:"mix_title"`
	Random_error  string `json:"random_error"`
	Random_title  string `json:"random_title"`
}

func GetEmoji(locale discord.Locale) EmojiTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["emoji"].(EmojiTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["emoji"].(EmojiTrad); ok {
			return t
		}
	}
	return EmojiTrad{}
}

type FunfactTrad struct {
	Source string `json:"source"`
	Title  string `json:"title"`
	Text   string `json:"text"`
}

func GetFunfact(locale discord.Locale) FunfactTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["funfact"].(FunfactTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["funfact"].(FunfactTrad); ok {
			return t
		}
	}
	return FunfactTrad{}
}

type GithubTrad struct {
	User_page    string `json:"user_page"`
	Repo_title   string `json:"repo_title"`
	Repo_desc    string `json:"repo_desc"`
	Repo_license string `json:"repo_license"`
	Repo_button  string `json:"repo_button"`
	No_desc      string `json:"no_desc"`
	None         string `json:"none"`
	User_title   string `json:"user_title"`
	Unknown      string `json:"unknown"`
}

func GetGithub(locale discord.Locale) GithubTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["github"].(GithubTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["github"].(GithubTrad); ok {
			return t
		}
	}
	return GithubTrad{}
}

type MathTrad struct {
	Title      string `json:"title"`
	Expression string `json:"expression"`
	Result     string `json:"result"`
}

func GetMath(locale discord.Locale) MathTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["math"].(MathTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["math"].(MathTrad); ok {
			return t
		}
	}
	return MathTrad{}
}

type MemeTrad struct {
	Meme_title string `json:"meme_title"`
	Author     string `json:"author"`
	Title      string `json:"title"`
}

func GetMeme(locale discord.Locale) MemeTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["meme"].(MemeTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["meme"].(MemeTrad); ok {
			return t
		}
	}
	return MemeTrad{}
}

type NasaTrad struct {
	Iss_altitude string `json:"iss_altitude"`
	Iss_updated  string `json:"iss_updated"`
	Apod_title   string `json:"apod_title"`
	Source       string `json:"source"`
	Iss_title    string `json:"iss_title"`
	Iss_position string `json:"iss_position"`
}

func GetNasa(locale discord.Locale) NasaTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["nasa"].(NasaTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["nasa"].(NasaTrad); ok {
			return t
		}
	}
	return NasaTrad{}
}

type NpmTrad struct {
	Unknown        string `json:"unknown"`
	Npm_page       string `json:"npm_page"`
	Title          string `json:"title"`
	Desc           string `json:"desc"`
	Downloads      string `json:"downloads"`
	Not_found      string `json:"not_found"`
	None           string `json:"none"`
	Repository     string `json:"repository"`
	Na             string `json:"na"`
	Last_published string `json:"last_published"`
}

func GetNpm(locale discord.Locale) NpmTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["npm"].(NpmTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["npm"].(NpmTrad); ok {
			return t
		}
	}
	return NpmTrad{}
}

type QuoteTrad struct {
	Title  string `json:"title"`
	Quote  string `json:"quote"`
	Author string `json:"author"`
}

func GetQuote(locale discord.Locale) QuoteTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["quote"].(QuoteTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["quote"].(QuoteTrad); ok {
			return t
		}
	}
	return QuoteTrad{}
}

type UpsidedownTrad struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

func GetUpsidedown(locale discord.Locale) UpsidedownTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["upsidedown"].(UpsidedownTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["upsidedown"].(UpsidedownTrad); ok {
			return t
		}
	}
	return UpsidedownTrad{}
}

type UrbanTrad struct {
	Title      string `json:"title"`
	Definition string `json:"definition"`
	Example    string `json:"example"`
	Author     string `json:"author"`
	Source     string `json:"source"`
}

func GetUrban(locale discord.Locale) UrbanTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["urban"].(UrbanTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["urban"].(UrbanTrad); ok {
			return t
		}
	}
	return UrbanTrad{}
}

type BotTrad struct {
	Stats             string `json:"stats"`
	Title             string `json:"title"`
	Description       string `json:"description"`
	Version_onyx      string `json:"version_onyx"`
	Last_boot         string `json:"last_boot"`
	Programming_title string `json:"programming_title"`
	Versions          string `json:"versions"`
	Db_size           string `json:"db_size"`
	Website           string `json:"website"`
	Details_title     string `json:"details_title"`
	Invite_me         string `json:"invite_me"`
	Error_self_user   string `json:"error_self_user"`
	Stats_title       string `json:"stats_title"`
}

func GetBot(locale discord.Locale) BotTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["bot"].(BotTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["bot"].(BotTrad); ok {
			return t
		}
	}
	return BotTrad{}
}

type SuggestionTrad struct {
}

func GetSuggestion(locale discord.Locale) SuggestionTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["suggestion"].(SuggestionTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["suggestion"].(SuggestionTrad); ok {
			return t
		}
	}
	return SuggestionTrad{}
}

type ReminderTrad struct {
	Snooze_button            string `json:"snooze_button"`
	Error_invalid_time       string `json:"error_invalid_time"`
	Create_success_desc      string `json:"create_success_desc"`
	Delete_success           string `json:"delete_success"`
	Edit_modal_title         string `json:"edit_modal_title"`
	Edit_success_title       string `json:"edit_success_title"`
	Snooze_success_desc      string `json:"snooze_success_desc"`
	Error_db                 string `json:"error_db"`
	Create_success_title     string `json:"create_success_title"`
	Edit_modal_content_label string `json:"edit_modal_content_label"`
	Edit_success_desc        string `json:"edit_success_desc"`
	List_empty               string `json:"list_empty"`
	Trigger_title            string `json:"trigger_title"`
	Snooze_success_title     string `json:"snooze_success_title"`
	Error_not_found          string `json:"error_not_found"`
	Error_generic            string `json:"error_generic"`
	Edit_modal_time_label    string `json:"edit_modal_time_label"`
	List_title               string `json:"list_title"`
	Error_limit_reached      string `json:"error_limit_reached"`
}

func GetReminder(locale discord.Locale) ReminderTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["reminder"].(ReminderTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["reminder"].(ReminderTrad); ok {
			return t
		}
	}
	return ReminderTrad{}
}

type PingTrad struct {
	Title           string `json:"title"`
	Gateway_latency string `json:"gateway_latency"`
	Rest_latency    string `json:"rest_latency"`
	Db_latency      string `json:"db_latency"`
}

func GetPing(locale discord.Locale) PingTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["ping"].(PingTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["ping"].(PingTrad); ok {
			return t
		}
	}
	return PingTrad{}
}

type TranslateTrad struct {
	Footer string `json:"footer"`
}

func GetTranslate(locale discord.Locale) TranslateTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["translate"].(TranslateTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["translate"].(TranslateTrad); ok {
			return t
		}
	}
	return TranslateTrad{}
}

type InteractionTrad struct {
	Not_allowed_component string `json:"not_allowed_component"`
	Not_allowed_modal     string `json:"not_allowed_modal"`
}

func GetInteraction(locale discord.Locale) InteractionTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["interaction"].(InteractionTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["interaction"].(InteractionTrad); ok {
			return t
		}
	}
	return InteractionTrad{}
}

type ModuleChannelCounterTrad struct {
}

func GetModule_ChannelCounter(locale discord.Locale) ModuleChannelCounterTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_ChannelCounter"].(ModuleChannelCounterTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_ChannelCounter"].(ModuleChannelCounterTrad); ok {
			return t
		}
	}
	return ModuleChannelCounterTrad{}
}

type ModuleFreeGamesModuleTrad struct {
}

func GetModule_FreeGamesModule(locale discord.Locale) ModuleFreeGamesModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_FreeGamesModule"].(ModuleFreeGamesModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_FreeGamesModule"].(ModuleFreeGamesModuleTrad); ok {
			return t
		}
	}
	return ModuleFreeGamesModuleTrad{}
}

type ModuleLoggingModuleTrad struct {
	BanRemove     ModuleLoggingModuleTrad_BanRemove     `json:"banRemove"`
	EmojiCreate   ModuleLoggingModuleTrad_EmojiCreate   `json:"emojiCreate"`
	StickerCreate ModuleLoggingModuleTrad_StickerCreate `json:"stickerCreate"`
	MessageDelete ModuleLoggingModuleTrad_MessageDelete `json:"messageDelete"`
	ThreadUpdate  ModuleLoggingModuleTrad_ThreadUpdate  `json:"threadUpdate"`
	RoleCreate    ModuleLoggingModuleTrad_RoleCreate    `json:"roleCreate"`
	MemberUpdate  ModuleLoggingModuleTrad_MemberUpdate  `json:"memberUpdate"`
	MemberLeave   ModuleLoggingModuleTrad_MemberLeave   `json:"memberLeave"`
	StickerUpdate ModuleLoggingModuleTrad_StickerUpdate `json:"stickerUpdate"`
	MessageUpdate ModuleLoggingModuleTrad_MessageUpdate `json:"messageUpdate"`
	ThreadCreate  ModuleLoggingModuleTrad_ThreadCreate  `json:"threadCreate"`
	ChannelCreate ModuleLoggingModuleTrad_ChannelCreate `json:"channelCreate"`
	ChannelDelete ModuleLoggingModuleTrad_ChannelDelete `json:"channelDelete"`
	RoleUpdate    ModuleLoggingModuleTrad_RoleUpdate    `json:"roleUpdate"`
	RoleDelete    ModuleLoggingModuleTrad_RoleDelete    `json:"roleDelete"`
	EmojiDelete   ModuleLoggingModuleTrad_EmojiDelete   `json:"emojiDelete"`
	InviteCreate  ModuleLoggingModuleTrad_InviteCreate  `json:"inviteCreate"`
	InviteDelete  ModuleLoggingModuleTrad_InviteDelete  `json:"inviteDelete"`
	ThreadDelete  ModuleLoggingModuleTrad_ThreadDelete  `json:"threadDelete"`
	ChannelUpdate ModuleLoggingModuleTrad_ChannelUpdate `json:"channelUpdate"`
	MemberJoin    ModuleLoggingModuleTrad_MemberJoin    `json:"memberJoin"`
	EmojiUpdate   ModuleLoggingModuleTrad_EmojiUpdate   `json:"emojiUpdate"`
	StickerDelete ModuleLoggingModuleTrad_StickerDelete `json:"stickerDelete"`
	GuildUpdate   ModuleLoggingModuleTrad_GuildUpdate   `json:"guildUpdate"`
	BanAdd        ModuleLoggingModuleTrad_BanAdd        `json:"banAdd"`
}

type ModuleLoggingModuleTrad_ChannelUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_ChannelUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ChannelUpdate_States struct {
	Name             string `json:"name"`
	Topic            string `json:"topic"`
	Nsfw             string `json:"nsfw"`
	RateLimitPerUser string `json:"rateLimitPerUser"`
}

type ModuleLoggingModuleTrad_MemberJoin struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_MemberJoin_States `json:"states"`
}

type ModuleLoggingModuleTrad_MemberJoin_States struct {
	User           string `json:"user"`
	AccountCreated string `json:"accountCreated"`
}

type ModuleLoggingModuleTrad_EmojiUpdate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiUpdate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_StickerDelete struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_StickerDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_StickerDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_GuildUpdate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_GuildUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_GuildUpdate_States struct {
	Name              string `json:"name"`
	Description       string `json:"description"`
	VerificationLevel string `json:"verificationLevel"`
	Icon              string `json:"icon"`
	Banner            string `json:"banner"`
}

type ModuleLoggingModuleTrad_BanAdd struct {
	Title  string                                `json:"title"`
	States ModuleLoggingModuleTrad_BanAdd_States `json:"states"`
}

type ModuleLoggingModuleTrad_BanAdd_States struct {
	Reason string `json:"reason"`
	User   string `json:"user"`
}

type ModuleLoggingModuleTrad_BanRemove struct {
	Title  string                                   `json:"title"`
	States ModuleLoggingModuleTrad_BanRemove_States `json:"states"`
}

type ModuleLoggingModuleTrad_BanRemove_States struct {
	User string `json:"user"`
}

type ModuleLoggingModuleTrad_EmojiCreate struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiCreate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_StickerCreate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_StickerCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_StickerCreate_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_MessageDelete struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_MessageDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_MessageDelete_States struct {
	Author  string `json:"author"`
	Channel string `json:"channel"`
	Content string `json:"content"`
}

type ModuleLoggingModuleTrad_ThreadUpdate struct {
	States ModuleLoggingModuleTrad_ThreadUpdate_States `json:"states"`
	Title  string                                      `json:"title"`
}

type ModuleLoggingModuleTrad_ThreadUpdate_States struct {
	Name                string `json:"name"`
	Archived            string `json:"archived"`
	Locked              string `json:"locked"`
	AutoArchiveDuration string `json:"autoArchiveDuration"`
}

type ModuleLoggingModuleTrad_RoleCreate struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleCreate_States struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type ModuleLoggingModuleTrad_MemberUpdate struct {
	States ModuleLoggingModuleTrad_MemberUpdate_States `json:"states"`
	Title  string                                      `json:"title"`
}

type ModuleLoggingModuleTrad_MemberUpdate_States struct {
	Roles    string `json:"roles"`
	Avatar   string `json:"avatar"`
	User     string `json:"user"`
	Nickname string `json:"nickname"`
}

type ModuleLoggingModuleTrad_MemberLeave struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_MemberLeave_States `json:"states"`
}

type ModuleLoggingModuleTrad_MemberLeave_States struct {
	User string `json:"user"`
}

type ModuleLoggingModuleTrad_StickerUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_StickerUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_StickerUpdate_States struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type ModuleLoggingModuleTrad_MessageUpdate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_MessageUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_MessageUpdate_States struct {
	Author     string `json:"author"`
	Channel    string `json:"channel"`
	OldContent string `json:"oldContent"`
	NewContent string `json:"newContent"`
}

type ModuleLoggingModuleTrad_ThreadCreate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_ThreadCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ThreadCreate_States struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Parent string `json:"parent"`
}

type ModuleLoggingModuleTrad_ChannelCreate struct {
	Title  string                                       `json:"title"`
	States ModuleLoggingModuleTrad_ChannelCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_ChannelCreate_States struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type ModuleLoggingModuleTrad_ChannelDelete struct {
	States ModuleLoggingModuleTrad_ChannelDelete_States `json:"states"`
	Title  string                                       `json:"title"`
}

type ModuleLoggingModuleTrad_ChannelDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_RoleUpdate struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleUpdate_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleUpdate_States struct {
	Permissions string `json:"permissions"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Hoist       string `json:"hoist"`
	Mentionable string `json:"mentionable"`
}

type ModuleLoggingModuleTrad_RoleDelete struct {
	Title  string                                    `json:"title"`
	States ModuleLoggingModuleTrad_RoleDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_RoleDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_EmojiDelete struct {
	Title  string                                     `json:"title"`
	States ModuleLoggingModuleTrad_EmojiDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_EmojiDelete_States struct {
	Name string `json:"name"`
}

type ModuleLoggingModuleTrad_InviteCreate struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_InviteCreate_States `json:"states"`
}

type ModuleLoggingModuleTrad_InviteCreate_States struct {
	MaxAge  string `json:"maxAge"`
	Code    string `json:"code"`
	Channel string `json:"channel"`
	Inviter string `json:"inviter"`
	MaxUses string `json:"maxUses"`
}

type ModuleLoggingModuleTrad_InviteDelete struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_InviteDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_InviteDelete_States struct {
	Code string `json:"code"`
}

type ModuleLoggingModuleTrad_ThreadDelete struct {
	Title  string                                      `json:"title"`
	States ModuleLoggingModuleTrad_ThreadDelete_States `json:"states"`
}

type ModuleLoggingModuleTrad_ThreadDelete_States struct {
	Name string `json:"name"`
}

func GetModule_LoggingModule(locale discord.Locale) ModuleLoggingModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_LoggingModule"].(ModuleLoggingModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_LoggingModule"].(ModuleLoggingModuleTrad); ok {
			return t
		}
	}
	return ModuleLoggingModuleTrad{}
}

type ModuleSafetyModuleTrad struct {
	Phishing_censored_title             string                            `json:"phishing_censored_title"`
	Nuke_masskick_alert                 string                            `json:"nuke_masskick_alert"`
	Nuke_success                        string                            `json:"nuke_success"`
	Log_title_captcha_failed            string                            `json:"log_title_captcha_failed"`
	Log_title_spam                      string                            `json:"log_title_spam"`
	Log_title_vanity                    string                            `json:"log_title_vanity"`
	Zalgo_censored_description          string                            `json:"zalgo_censored_description"`
	Mention_spam_censored_title         string                            `json:"mention_spam_censored_title"`
	Emojis_spam_censored_title          string                            `json:"emojis_spam_censored_title"`
	Log_title_captcha_sent              string                            `json:"log_title_captcha_sent"`
	Log_title_nuke                      string                            `json:"log_title_nuke"`
	Log_title_bot                       string                            `json:"log_title_bot"`
	Emojis_spam_censored_description    string                            `json:"emojis_spam_censored_description"`
	Vanity_nuke_alert                   string                            `json:"vanity_nuke_alert"`
	Log_title_zalgo                     string                            `json:"log_title_zalgo"`
	Log_title_alt                       string                            `json:"log_title_alt"`
	Log_title_phishing                  string                            `json:"log_title_phishing"`
	Log_title_invite                    string                            `json:"log_title_invite"`
	Phishing_censored_description       string                            `json:"phishing_censored_description"`
	Mention_spam_censored_description   string                            `json:"mention_spam_censored_description"`
	Nuke_massedit_alert                 string                            `json:"nuke_massedit_alert"`
	Log_title_captcha_passed            string                            `json:"log_title_captcha_passed"`
	Log_title_emoji                     string                            `json:"log_title_emoji"`
	Zalgo_censored_title                string                            `json:"zalgo_censored_title"`
	Log_title_raid                      string                            `json:"log_title_raid"`
	Blocked_invite_censored_description string                            `json:"blocked_invite_censored_description"`
	Blocked_invite_censored_title       string                            `json:"blocked_invite_censored_title"`
	Nuke_massdelete_alert               string                            `json:"nuke_massdelete_alert"`
	Nuke_fail                           string                            `json:"nuke_fail"`
	Log_title_mention                   string                            `json:"log_title_mention"`
	Log_title_danger_perm               string                            `json:"log_title_danger_perm"`
	Log_fields                          ModuleSafetyModuleTrad_Log_fields `json:"log_fields"`
}

type ModuleSafetyModuleTrad_Log_fields struct {
	User                      string `json:"user"`
	Bot_kicked                string `json:"bot_kicked"`
	Created_ago               string `json:"created_ago"`
	Level_activated           string `json:"level_activated"`
	Zalgo_ratio               string `json:"zalgo_ratio"`
	Infraction_code           string `json:"infraction_code"`
	Status_vanity             string `json:"status_vanity"`
	Author                    string `json:"author"`
	Action_deleted_timeout    string `json:"action_deleted_timeout"`
	Nuke_action               string `json:"nuke_action"`
	Nuke_result               string `json:"nuke_result"`
	Target                    string `json:"target"`
	Captcha_expired           string `json:"captcha_expired"`
	Level_triggered           string `json:"level_triggered"`
	Captcha_failed            string `json:"captcha_failed"`
	Action_deleted_quarantine string `json:"action_deleted_quarantine"`
	Action_vanity             string `json:"action_vanity"`
	Action_danger_perm        string `json:"action_danger_perm"`
}

func GetModule_SafetyModule(locale discord.Locale) ModuleSafetyModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_SafetyModule"].(ModuleSafetyModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_SafetyModule"].(ModuleSafetyModuleTrad); ok {
			return t
		}
	}
	return ModuleSafetyModuleTrad{}
}

type ModuleSocialNotifsModuleTrad struct {
}

func GetModule_SocialNotifsModule(locale discord.Locale) ModuleSocialNotifsModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_SocialNotifsModule"].(ModuleSocialNotifsModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_SocialNotifsModule"].(ModuleSocialNotifsModuleTrad); ok {
			return t
		}
	}
	return ModuleSocialNotifsModuleTrad{}
}

type ModuleSuggestionModuleTrad struct {
	Thread_name                string `json:"thread_name"`
	Error_channel_not_found    string `json:"error_channel_not_found"`
	Error_send_failed          string `json:"error_send_failed"`
	Modal_desc_placeholder     string `json:"modal_desc_placeholder"`
	Submit_footer              string `json:"submit_footer"`
	Error_invalid_channel_type string `json:"error_invalid_channel_type"`
	Sub_submit_name            string `json:"sub_submit_name"`
	Sub_submit_description     string `json:"sub_submit_description"`
	Modal_title_placeholder    string `json:"modal_title_placeholder"`
	Modal_desc_label           string `json:"modal_desc_label"`
	Suggestion_from            string `json:"suggestion_from"`
	Success_title              string `json:"success_title"`
	Cmd_description            string `json:"cmd_description"`
	Modal_title                string `json:"modal_title"`
	Modal_title_label          string `json:"modal_title_label"`
	Modal_images_label         string `json:"modal_images_label"`
	Success_desc               string `json:"success_desc"`
	Cmd_name                   string `json:"cmd_name"`
}

func GetModule_SuggestionModule(locale discord.Locale) ModuleSuggestionModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_SuggestionModule"].(ModuleSuggestionModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_SuggestionModule"].(ModuleSuggestionModuleTrad); ok {
			return t
		}
	}
	return ModuleSuggestionModuleTrad{}
}

type ModuleTranslationModuleTrad struct {
}

func GetModule_TranslationModule(locale discord.Locale) ModuleTranslationModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_TranslationModule"].(ModuleTranslationModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_TranslationModule"].(ModuleTranslationModuleTrad); ok {
			return t
		}
	}
	return ModuleTranslationModuleTrad{}
}

type ModuleWelcomeModuleTrad struct {
	Leave_card_t2      string `json:"leave_card_t2"`
	Leave_embed_title  string `json:"leave_embed_title"`
	Leave_embed_footer string `json:"leave_embed_footer"`
	Card_t1            string `json:"card_t1"`
	Card_t2            string `json:"card_t2"`
	Embed_title        string `json:"embed_title"`
	Embed_footer       string `json:"embed_footer"`
	Leave_card_t1      string `json:"leave_card_t1"`
}

func GetModule_WelcomeModule(locale discord.Locale) ModuleWelcomeModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_WelcomeModule"].(ModuleWelcomeModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_WelcomeModule"].(ModuleWelcomeModuleTrad); ok {
			return t
		}
	}
	return ModuleWelcomeModuleTrad{}
}

type ModuleWizzardModuleTrad struct {
	Spells ModuleWizzardModuleTrad_Spells `json:"spells"`
}

type ModuleWizzardModuleTrad_Spells struct {
	Lacarnuminflammari    ModuleWizzardModuleTrad_Spells_Lacarnuminflammari    `json:"lacarnuminflammari"`
	Waddiwasi             ModuleWizzardModuleTrad_Spells_Waddiwasi             `json:"waddiwasi"`
	Amplificatum          ModuleWizzardModuleTrad_Spells_Amplificatum          `json:"amplificatum"`
	Aparecium             ModuleWizzardModuleTrad_Spells_Aparecium             `json:"aparecium"`
	Impedimenta           ModuleWizzardModuleTrad_Spells_Impedimenta           `json:"impedimenta"`
	Nox                   ModuleWizzardModuleTrad_Spells_Nox                   `json:"nox"`
	Reparo                ModuleWizzardModuleTrad_Spells_Reparo                `json:"reparo"`
	Expectopatronum       ModuleWizzardModuleTrad_Spells_Expectopatronum       `json:"expectopatronum"`
	Homomorphus           ModuleWizzardModuleTrad_Spells_Homomorphus           `json:"homomorphus"`
	Prioriincantatum      ModuleWizzardModuleTrad_Spells_Prioriincantatum      `json:"prioriincantatum"`
	Assurdiato            ModuleWizzardModuleTrad_Spells_Assurdiato            `json:"assurdiato"`
	Liberacorpus          ModuleWizzardModuleTrad_Spells_Liberacorpus          `json:"liberacorpus"`
	Tarentallegra         ModuleWizzardModuleTrad_Spells_Tarentallegra         `json:"tarentallegra"`
	Harmonianecterepassus ModuleWizzardModuleTrad_Spells_Harmonianecterepassus `json:"harmonianecterepassus"`
	Avadakedavra          ModuleWizzardModuleTrad_Spells_Avadakedavra          `json:"avadakedavra"`
	Fidelitas             ModuleWizzardModuleTrad_Spells_Fidelitas             `json:"fidelitas"`
	Oubliettes            ModuleWizzardModuleTrad_Spells_Oubliettes            `json:"oubliettes"`
	Protegomaxima         ModuleWizzardModuleTrad_Spells_Protegomaxima         `json:"protegomaxima"`
	Surgito               ModuleWizzardModuleTrad_Spells_Surgito               `json:"surgito"`
	Specialisrevelio      ModuleWizzardModuleTrad_Spells_Specialisrevelio      `json:"specialisrevelio"`
	Accio                 ModuleWizzardModuleTrad_Spells_Accio                 `json:"accio"`
	Cistemaperio          ModuleWizzardModuleTrad_Spells_Cistemaperio          `json:"cistemaperio"`
	Enervatum             ModuleWizzardModuleTrad_Spells_Enervatum             `json:"enervatum"`
	Priorincanto          ModuleWizzardModuleTrad_Spells_Priorincanto          `json:"priorincanto"`
	Riddikulus            ModuleWizzardModuleTrad_Spells_Riddikulus            `json:"riddikulus"`
	Wingardiumleviosa     ModuleWizzardModuleTrad_Spells_Wingardiumleviosa     `json:"wingardiumleviosa"`
	Alohomora             ModuleWizzardModuleTrad_Spells_Alohomora             `json:"alohomora"`
	Brachiumemendo        ModuleWizzardModuleTrad_Spells_Brachiumemendo        `json:"brachiumemendo"`
	Duro                  ModuleWizzardModuleTrad_Spells_Duro                  `json:"duro"`
	Emancipare            ModuleWizzardModuleTrad_Spells_Emancipare            `json:"emancipare"`
	Meteorribilisrecanto  ModuleWizzardModuleTrad_Spells_Meteorribilisrecanto  `json:"meteorribilisrecanto"`
	Mobilicorpus          ModuleWizzardModuleTrad_Spells_Mobilicorpus          `json:"mobilicorpus"`
	Incendio              ModuleWizzardModuleTrad_Spells_Incendio              `json:"incendio"`
	Obscuro               ModuleWizzardModuleTrad_Spells_Obscuro               `json:"obscuro"`
	Rictusempra           ModuleWizzardModuleTrad_Spells_Rictusempra           `json:"rictusempra"`
	Evertestatum          ModuleWizzardModuleTrad_Spells_Evertestatum          `json:"evertestatum"`
	Locomotorbarda        ModuleWizzardModuleTrad_Spells_Locomotorbarda        `json:"locomotorbarda"`
	Defodio               ModuleWizzardModuleTrad_Spells_Defodio               `json:"defodio"`
	Dentesaugmento        ModuleWizzardModuleTrad_Spells_Dentesaugmento        `json:"dentesaugmento"`
	Diffindo              ModuleWizzardModuleTrad_Spells_Diffindo              `json:"diffindo"`
	Ferula                ModuleWizzardModuleTrad_Spells_Ferula                `json:"ferula"`
	Reducto               ModuleWizzardModuleTrad_Spells_Reducto               `json:"reducto"`
	Serpensortia          ModuleWizzardModuleTrad_Spells_Serpensortia          `json:"serpensortia"`
	Silencio              ModuleWizzardModuleTrad_Spells_Silencio              `json:"silencio"`
	Speropatronum         ModuleWizzardModuleTrad_Spells_Speropatronum         `json:"speropatronum"`
	Avensegium            ModuleWizzardModuleTrad_Spells_Avensegium            `json:"avensegium"`
	Circumrota            ModuleWizzardModuleTrad_Spells_Circumrota            `json:"circumrota"`
	Impero                ModuleWizzardModuleTrad_Spells_Impero                `json:"impero"`
	Salveomaleficia       ModuleWizzardModuleTrad_Spells_Salveomaleficia       `json:"salveomaleficia"`
	Viperaevanesca        ModuleWizzardModuleTrad_Spells_Viperaevanesca        `json:"viperaevanesca"`
	Brachialigo           ModuleWizzardModuleTrad_Spells_Brachialigo           `json:"brachialigo"`
	Deprimo               ModuleWizzardModuleTrad_Spells_Deprimo               `json:"deprimo"`
	Dissendium            ModuleWizzardModuleTrad_Spells_Dissendium            `json:"dissendium"`
	Locomotorwibbly       ModuleWizzardModuleTrad_Spells_Locomotorwibbly       `json:"locomotorwibbly"`
	Protegototalum        ModuleWizzardModuleTrad_Spells_Protegototalum        `json:"protegototalum"`
	Aberto                ModuleWizzardModuleTrad_Spells_Aberto                `json:"aberto"`
	Apparevestigium       ModuleWizzardModuleTrad_Spells_Apparevestigium       `json:"apparevestigium"`
	Erigo                 ModuleWizzardModuleTrad_Spells_Erigo                 `json:"erigo"`
	Expelliarmus          ModuleWizzardModuleTrad_Spells_Expelliarmus          `json:"expelliarmus"`
	Oppugno               ModuleWizzardModuleTrad_Spells_Oppugno               `json:"oppugno"`
	Veraverto             ModuleWizzardModuleTrad_Spells_Veraverto             `json:"veraverto"`
	Furunculus            ModuleWizzardModuleTrad_Spells_Furunculus            `json:"furunculus"`
	Protegodiabolica      ModuleWizzardModuleTrad_Spells_Protegodiabolica      `json:"protegodiabolica"`
	Stupefix              ModuleWizzardModuleTrad_Spells_Stupefix              `json:"stupefix"`
	Vulnerasanentur       ModuleWizzardModuleTrad_Spells_Vulnerasanentur       `json:"vulnerasanentur"`
	Araniaexumai          ModuleWizzardModuleTrad_Spells_Araniaexumai          `json:"araniaexumai"`
	Gemino                ModuleWizzardModuleTrad_Spells_Gemino                `json:"gemino"`
	Impervius             ModuleWizzardModuleTrad_Spells_Impervius             `json:"impervius"`
	Repellomoldum         ModuleWizzardModuleTrad_Spells_Repellomoldum         `json:"repellomoldum"`
	Arrestomomentum       ModuleWizzardModuleTrad_Spells_Arrestomomentum       `json:"arrestomomentum"`
	Fulgari               ModuleWizzardModuleTrad_Spells_Fulgari               `json:"fulgari"`
	Petrificustotalus     ModuleWizzardModuleTrad_Spells_Petrificustotalus     `json:"petrificustotalus"`
	Legilimens            ModuleWizzardModuleTrad_Spells_Legilimens            `json:"legilimens"`
	Mutinlutinmalinpesti  ModuleWizzardModuleTrad_Spells_Mutinlutinmalinpesti  `json:"mutinlutinmalinpesti"`
	Revigor               ModuleWizzardModuleTrad_Spells_Revigor               `json:"revigor"`
	Revelio               ModuleWizzardModuleTrad_Spells_Revelio               `json:"revelio"`
	Bombardamaxima        ModuleWizzardModuleTrad_Spells_Bombardamaxima        `json:"bombardamaxima"`
	Destructum            ModuleWizzardModuleTrad_Spells_Destructum            `json:"destructum"`
	Flambios              ModuleWizzardModuleTrad_Spells_Flambios              `json:"flambios"`
	Sonorus               ModuleWizzardModuleTrad_Spells_Sonorus               `json:"sonorus"`
	Tergeo                ModuleWizzardModuleTrad_Spells_Tergeo                `json:"tergeo"`
	Aguamenti             ModuleWizzardModuleTrad_Spells_Aguamenti             `json:"aguamenti"`
	Evanesco              ModuleWizzardModuleTrad_Spells_Evanesco              `json:"evanesco"`
	Fiantoduri            ModuleWizzardModuleTrad_Spells_Fiantoduri            `json:"fiantoduri"`
	Finiteincantatem      ModuleWizzardModuleTrad_Spells_Finiteincantatem      `json:"finiteincantatem"`
	Reverte               ModuleWizzardModuleTrad_Spells_Reverte               `json:"reverte"`
	Slugvomitingcharm     ModuleWizzardModuleTrad_Spells_Slugvomitingcharm     `json:"slugvomitingcharm"`
	Morsmordre            ModuleWizzardModuleTrad_Spells_Morsmordre            `json:"morsmordre"`
	Orchideus             ModuleWizzardModuleTrad_Spells_Orchideus             `json:"orchideus"`
	Oscausi               ModuleWizzardModuleTrad_Spells_Oscausi               `json:"oscausi"`
	Protego               ModuleWizzardModuleTrad_Spells_Protego               `json:"protego"`
	Anapneo               ModuleWizzardModuleTrad_Spells_Anapneo               `json:"anapneo"`
	Volateascendere       ModuleWizzardModuleTrad_Spells_Volateascendere       `json:"volateascendere"`
	Capaciousextremis     ModuleWizzardModuleTrad_Spells_Capaciousextremis     `json:"capaciousextremis"`
	Glisseo               ModuleWizzardModuleTrad_Spells_Glisseo               `json:"glisseo"`
	Levicorpus            ModuleWizzardModuleTrad_Spells_Levicorpus            `json:"levicorpus"`
	Molliare              ModuleWizzardModuleTrad_Spells_Molliare              `json:"molliare"`
	Nebulus               ModuleWizzardModuleTrad_Spells_Nebulus               `json:"nebulus"`
	Recurvite             ModuleWizzardModuleTrad_Spells_Recurvite             `json:"recurvite"`
	Repelloinimicium      ModuleWizzardModuleTrad_Spells_Repelloinimicium      `json:"repelloinimicium"`
	Hominumrevelio        ModuleWizzardModuleTrad_Spells_Hominumrevelio        `json:"hominumrevelio"`
	Incarcerem            ModuleWizzardModuleTrad_Spells_Incarcerem            `json:"incarcerem"`
	Collaporta            ModuleWizzardModuleTrad_Spells_Collaporta            `json:"collaporta"`
	Confringo             ModuleWizzardModuleTrad_Spells_Confringo             `json:"confringo"`
	Locomotormortis       ModuleWizzardModuleTrad_Spells_Locomotormortis       `json:"locomotormortis"`
	Partistemporus        ModuleWizzardModuleTrad_Spells_Partistemporus        `json:"partistemporus"`
	Failamalle            ModuleWizzardModuleTrad_Spells_Failamalle            `json:"failamalle"`
	Piertotumlocomotor    ModuleWizzardModuleTrad_Spells_Piertotumlocomotor    `json:"piertotumlocomotor"`
	Portus                ModuleWizzardModuleTrad_Spells_Portus                `json:"portus"`
	Fenestra              ModuleWizzardModuleTrad_Spells_Fenestra              `json:"fenestra"`
	Periculum             ModuleWizzardModuleTrad_Spells_Periculum             `json:"periculum"`
	Bloclang              ModuleWizzardModuleTrad_Spells_Bloclang              `json:"bloclang"`
	Endoloris             ModuleWizzardModuleTrad_Spells_Endoloris             `json:"endoloris"`
	Episkey               ModuleWizzardModuleTrad_Spells_Episkey               `json:"episkey"`
	Surdinam              ModuleWizzardModuleTrad_Spells_Surdinam              `json:"surdinam"`
	Avis                  ModuleWizzardModuleTrad_Spells_Avis                  `json:"avis"`
	Expulso               ModuleWizzardModuleTrad_Spells_Expulso               `json:"expulso"`
	Mobiliarbus           ModuleWizzardModuleTrad_Spells_Mobiliarbus           `json:"mobiliarbus"`
	Sectumsempra          ModuleWizzardModuleTrad_Spells_Sectumsempra          `json:"sectumsempra"`
	Ascendio              ModuleWizzardModuleTrad_Spells_Ascendio              `json:"ascendio"`
	Caveinimicum          ModuleWizzardModuleTrad_Spells_Caveinimicum          `json:"caveinimicum"`
	Immobulus             ModuleWizzardModuleTrad_Spells_Immobulus             `json:"immobulus"`
	Confundo              ModuleWizzardModuleTrad_Spells_Confundo              `json:"confundo"`
	Protegohorribilis     ModuleWizzardModuleTrad_Spells_Protegohorribilis     `json:"protegohorribilis"`
	Ventus                ModuleWizzardModuleTrad_Spells_Ventus                `json:"ventus"`
}

type ModuleWizzardModuleTrad_Spells_Stupefix struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Vulnerasanentur struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Araniaexumai struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Gemino struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Impervius struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Repellomoldum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Arrestomomentum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fulgari struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Petrificustotalus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Legilimens struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Mutinlutinmalinpesti struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Revigor struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Revelio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Bombardamaxima struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Destructum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Flambios struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Sonorus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Tergeo struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Aguamenti struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Evanesco struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Fiantoduri struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Finiteincantatem struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Reverte struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Slugvomitingcharm struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Morsmordre struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Orchideus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Oscausi struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protego struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Anapneo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Volateascendere struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Capaciousextremis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Glisseo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Levicorpus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Molliare struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Nebulus struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Recurvite struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Repelloinimicium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Hominumrevelio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Incarcerem struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Collaporta struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Confringo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Locomotormortis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Partistemporus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Failamalle struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Piertotumlocomotor struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Portus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Fenestra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Periculum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Bloclang struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Endoloris struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Episkey struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Surdinam struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Avis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Expulso struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Mobiliarbus struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Sectumsempra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Ascendio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Caveinimicum struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Immobulus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Confundo struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Protegohorribilis struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Ventus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Lacarnuminflammari struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Waddiwasi struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Amplificatum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Aparecium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Impedimenta struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Nox struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Reparo struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Expectopatronum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Homomorphus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Prioriincantatum struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Assurdiato struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Liberacorpus struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Tarentallegra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Harmonianecterepassus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Avadakedavra struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Fidelitas struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Oubliettes struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protegomaxima struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Surgito struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Specialisrevelio struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Accio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Cistemaperio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Enervatum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Priorincanto struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Riddikulus struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Wingardiumleviosa struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Alohomora struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Brachiumemendo struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Duro struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Emancipare struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Meteorribilisrecanto struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Mobilicorpus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Incendio struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Obscuro struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Rictusempra struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Evertestatum struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Locomotorbarda struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Defodio struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Dentesaugmento struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Diffindo struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Ferula struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Reducto struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Serpensortia struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Silencio struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Speropatronum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Avensegium struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Circumrota struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Impero struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Salveomaleficia struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Viperaevanesca struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Brachialigo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Deprimo struct {
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
}

type ModuleWizzardModuleTrad_Spells_Dissendium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Locomotorwibbly struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Protegototalum struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Aberto struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

type ModuleWizzardModuleTrad_Spells_Apparevestigium struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Erigo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Expelliarmus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Oppugno struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Veraverto struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
	Fail        string `json:"fail"`
}

type ModuleWizzardModuleTrad_Spells_Furunculus struct {
	Success     string `json:"success"`
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ModuleWizzardModuleTrad_Spells_Protegodiabolica struct {
	Fail        string `json:"fail"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Success     string `json:"success"`
}

func GetModule_WizzardModule(locale discord.Locale) ModuleWizzardModuleTrad {
	if l, ok := localizations[locale]; ok {
		if t, ok := l["module_WizzardModule"].(ModuleWizzardModuleTrad); ok {
			return t
		}
	}
	if l, ok := localizations[discord.LocaleEnglishUS]; ok {
		if t, ok := l["module_WizzardModule"].(ModuleWizzardModuleTrad); ok {
			return t
		}
	}
	return ModuleWizzardModuleTrad{}
}
